export interface GalleryImage {
  id: string
  title: string
  category: string[]
  description?: string
  imageUrl: string
  thumbnailUrl: string
  alt: string
}

export const staticGallery: GalleryImage[] = [
  // Events
  { id: '1', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-01.jpg', thumbnailUrl: '/gallery/photo-01.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '2', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-02.jpg', thumbnailUrl: '/gallery/photo-02.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '3', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-03.jpg', thumbnailUrl: '/gallery/photo-03.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '4', title: 'Scottish Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-04.jpg', thumbnailUrl: '/gallery/photo-04.jpg', alt: 'Scottish Highland Cattle at Moonlight Run Farm' },
  { id: '5', title: 'Llama', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-05.jpg', thumbnailUrl: '/gallery/photo-05.jpg', alt: 'Llama at Moonlight Run Farm' },
  { id: '6', title: 'Llama', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-06.jpg', thumbnailUrl: '/gallery/photo-06.jpg', alt: 'Llama at Moonlight Run Farm' },
  { id: '7', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-07.jpg', thumbnailUrl: '/gallery/photo-07.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '8', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-08.jpg', thumbnailUrl: '/gallery/photo-08.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '9', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-09.jpg', thumbnailUrl: '/gallery/photo-09.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '10', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-10.jpg', thumbnailUrl: '/gallery/photo-10.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '11', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-11.jpg', thumbnailUrl: '/gallery/photo-11.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '12', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-12.jpg', thumbnailUrl: '/gallery/photo-12.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '13', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-13.jpg', thumbnailUrl: '/gallery/photo-13.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '14', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-14.jpg', thumbnailUrl: '/gallery/photo-14.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '15', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-15.jpg', thumbnailUrl: '/gallery/photo-15.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '16', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-16.jpg', thumbnailUrl: '/gallery/photo-16.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '17', title: 'Nigerian Dwarf Goat', category: ['goats'], imageUrl: '/gallery/photo-17.jpg', thumbnailUrl: '/gallery/photo-17.jpg', alt: 'Nigerian Dwarf Goat at Moonlight Run Farm' },
  { id: '18', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-18.jpg', thumbnailUrl: '/gallery/photo-18.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '19', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-19.jpg', thumbnailUrl: '/gallery/photo-19.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '20', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-20.jpg', thumbnailUrl: '/gallery/photo-20.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '21', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-21.jpg', thumbnailUrl: '/gallery/photo-21.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '22', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-22.jpg', thumbnailUrl: '/gallery/photo-22.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '23', title: 'Alpaca', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-23.jpg', thumbnailUrl: '/gallery/photo-23.jpg', alt: 'Alpaca at Moonlight Run Farm' },
  { id: '24', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-24.jpg', thumbnailUrl: '/gallery/photo-24.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '25', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-25.jpg', thumbnailUrl: '/gallery/photo-25.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '26', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-26.jpg', thumbnailUrl: '/gallery/photo-26.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '27', title: 'Llama', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-27.jpg', thumbnailUrl: '/gallery/photo-27.jpg', alt: 'Llama at Moonlight Run Farm' },
  { id: '28', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-28.jpg', thumbnailUrl: '/gallery/photo-28.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '29', title: 'Alpaca', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-29.jpg', thumbnailUrl: '/gallery/photo-29.jpg', alt: 'Alpaca at Moonlight Run Farm' },
  { id: '30', title: 'Llama', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-30.jpg', thumbnailUrl: '/gallery/photo-30.jpg', alt: 'Llama at Moonlight Run Farm' },
  { id: '31', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-31.jpg', thumbnailUrl: '/gallery/photo-31.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '32', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-32.jpg', thumbnailUrl: '/gallery/photo-32.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '33', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-33.jpg', thumbnailUrl: '/gallery/photo-33.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '34', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-34.jpg', thumbnailUrl: '/gallery/photo-34.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '36', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-36.jpg', thumbnailUrl: '/gallery/photo-36.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '37', title: 'Alpaca', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-37.jpg', thumbnailUrl: '/gallery/photo-37.jpg', alt: 'Alpaca at Moonlight Run Farm' },
  { id: '38', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-38.jpg', thumbnailUrl: '/gallery/photo-38.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '39', title: 'Llama', category: ['llamas-alpaca'], imageUrl: '/gallery/photo-39.jpg', thumbnailUrl: '/gallery/photo-39.jpg', alt: 'Llama at Moonlight Run Farm' },
  { id: '40', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-40.jpg', thumbnailUrl: '/gallery/photo-40.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '41', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-41.jpg', thumbnailUrl: '/gallery/photo-41.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '42', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-42.jpg', thumbnailUrl: '/gallery/photo-42.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '43', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-43.jpg', thumbnailUrl: '/gallery/photo-43.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '44', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-44.jpg', thumbnailUrl: '/gallery/photo-44.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '45', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-45.jpg', thumbnailUrl: '/gallery/photo-45.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '46', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-46.jpg', thumbnailUrl: '/gallery/photo-46.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '47', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-47.jpg', thumbnailUrl: '/gallery/photo-47.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '48', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-48.jpg', thumbnailUrl: '/gallery/photo-48.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '49', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-49.jpg', thumbnailUrl: '/gallery/photo-49.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '50', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-50.jpg', thumbnailUrl: '/gallery/photo-50.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '51', title: 'Highland Cattle', category: ['cattle'], imageUrl: '/gallery/photo-51.jpg', thumbnailUrl: '/gallery/photo-51.jpg', alt: 'Highland Cattle at Moonlight Run Farm' },
  { id: '52', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-52.jpg', thumbnailUrl: '/gallery/photo-52.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '53', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-53.jpg', thumbnailUrl: '/gallery/photo-53.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '54', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-54.jpg', thumbnailUrl: '/gallery/photo-54.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '55', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-55.jpg', thumbnailUrl: '/gallery/photo-55.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '56', title: 'Farm Event', category: ['events'], imageUrl: '/gallery/photo-56.jpg', thumbnailUrl: '/gallery/photo-56.jpg', alt: 'Event at Moonlight Run Farm' },
  { id: '57', title: 'Farm Life', category: ['farm-life'], imageUrl: '/gallery/photo-57.jpg', thumbnailUrl: '/gallery/photo-57.jpg', alt: 'Life at Moonlight Run Farm' },
  { id: '58', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-58.jpg', thumbnailUrl: '/gallery/photo-58.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '59', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-59.jpg', thumbnailUrl: '/gallery/photo-59.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '60', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-60.jpg', thumbnailUrl: '/gallery/photo-60.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '61', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-61.jpg', thumbnailUrl: '/gallery/photo-61.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '62', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-62.jpg', thumbnailUrl: '/gallery/photo-62.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '63', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-63.jpg', thumbnailUrl: '/gallery/photo-63.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '64', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-64.jpg', thumbnailUrl: '/gallery/photo-64.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '65', title: 'Poultry', category: ['poultry'], imageUrl: '/gallery/photo-65.jpg', thumbnailUrl: '/gallery/photo-65.jpg', alt: 'Poultry at Moonlight Run Farm' },
  { id: '67', title: 'Farm Fresh Eggs', category: ['poultry'], imageUrl: '/gallery/photo-67.jpg', thumbnailUrl: '/gallery/photo-67.jpg', alt: 'Colorful farm fresh eggs from Moonlight Run Farm' },
  { id: '69', title: 'Muscovy Duck', category: ['poultry'], imageUrl: '/gallery/photo-69.jpg', thumbnailUrl: '/gallery/photo-69.jpg', alt: 'Muscovy Duck at Moonlight Run Farm' },
  { id: '70', title: 'Muscovy Duck', category: ['poultry'], imageUrl: '/gallery/photo-70.jpg', thumbnailUrl: '/gallery/photo-70.jpg', alt: 'Muscovy Duck at Moonlight Run Farm' },
  { id: '71', title: 'Highland Bull', category: ['cattle'], imageUrl: '/gallery/photo-71.jpg', thumbnailUrl: '/gallery/photo-71.jpg', alt: 'Scottish Highland Bull at Moonlight Run Farm' },
  { id: '72', title: 'Yaks', category: ['cattle'], imageUrl: '/gallery/photo-72.jpg', thumbnailUrl: '/gallery/photo-72.jpg', alt: 'Yaks eating hay in the snow at Moonlight Run Farm' },
  { id: '73', title: 'Llama', category: ['farm-life'], imageUrl: '/gallery/photo-73.jpg', thumbnailUrl: '/gallery/photo-73.jpg', alt: 'Llama close-up at Moonlight Run Farm' },
  { id: '74', title: 'Llamas & Goats', category: ['farm-life'], imageUrl: '/gallery/photo-74.jpg', thumbnailUrl: '/gallery/photo-74.jpg', alt: 'Llamas and goats at the fence at Moonlight Run Farm' },
  { id: '75', title: 'Llamas & Goats', category: ['farm-life'], imageUrl: '/gallery/photo-75.jpg', thumbnailUrl: '/gallery/photo-75.jpg', alt: 'Llamas and goats in the snow at Moonlight Run Farm' },
  { id: '76', title: 'Yaks at Dusk', category: ['cattle'], imageUrl: '/gallery/photo-76.jpg', thumbnailUrl: '/gallery/photo-76.jpg', alt: 'Two yaks at dusk in the snow at Moonlight Run Farm' },
]
