/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'api-keys': ApiKey;
    media: Media;
    pages: Page;
    services: Service;
    gallery: Gallery;
    events: Event;
    products: Product;
    testimonials: Testimonial;
    team: Team;
    documents: Document;
    'inquiry-flow-config': InquiryFlowConfig;
    'inquiry-submissions': InquirySubmission;
    'site-settings': SiteSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'inquiry-flow-config': InquiryFlowConfigSelect<false> | InquiryFlowConfigSelect<true>;
    'inquiry-submissions': InquirySubmissionsSelect<false> | InquirySubmissionsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g., moonlight-farm)
   */
  slug: string;
  /**
   * Client site domain (e.g., moonlightrunfarm.com)
   */
  domain?: string | null;
  status: 'active' | 'suspended' | 'pending';
  siteType: 'farm' | 'contractor' | 'restaurant' | 'general';
  ownerEmail: string;
  ownerName?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  roles: ('super_admin' | 'client_admin' | 'client_editor')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  /**
   * SHA-256 hash of the API key
   */
  keyHash: string;
  /**
   * First 8 characters for identification (e.g., "client_ab")
   */
  keyPrefix: string;
  tenant: number | Tenant;
  status: 'active' | 'revoked' | 'expired';
  rateLimit?: number | null;
  lastUsedAt?: string | null;
  expiresAt?: string | null;
  /**
   * Optional note about this key
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Describe this image for accessibility
   */
  alt: string;
  category?:
    | (
        | 'cattle'
        | 'goats'
        | 'llamas-alpaca'
        | 'poultry'
        | 'dogs'
        | 'other-animals'
        | 'farm'
        | 'events'
        | 'products'
        | 'team'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL path (e.g., "about" becomes /about)
   */
  slug: string;
  heroHeading?: string | null;
  heroSubheading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Leave blank to use page title
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief summary for cards (2-3 sentences)
   */
  shortDescription?: string | null;
  category:
    | 'transport'
    | 'education'
    | 'petting-zoo'
    | 'livestock-services'
    | 'boarding'
    | 'animal-sales'
    | 'special-events'
    | 'other';
  /**
   * e.g., "Starting at $150" or "Contact for quote"
   */
  pricingText?: string | null;
  /**
   * Links to inquiry wizard branch (e.g., "hauling", "events")
   */
  inquiryType?: string | null;
  /**
   * Icon identifier for the frontend
   */
  icon?: string | null;
  image?: (number | null) | Media;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  image: number | Media;
  /**
   * Overrides the media alt text for this gallery context
   */
  altText?: string | null;
  category: (
    | 'cattle'
    | 'goats'
    | 'llamas-alpaca'
    | 'donkeys'
    | 'poultry'
    | 'dogs'
    | 'rabbits'
    | 'farm-life'
    | 'events'
    | 'products'
  )[];
  description?: string | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  startTime: string;
  endTime?: string | null;
  location?: string | null;
  image?: (number | null) | Media;
  /**
   * Auto-synced from Facebook if available
   */
  facebookEventId?: string | null;
  facebookEventUrl?: string | null;
  registrationUrl?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  category: 'beef' | 'poultry' | 'eggs' | 'hay' | 'fiber' | 'other';
  /**
   * e.g., "$8.50/lb" or "Contact for pricing"
   */
  price?: string | null;
  /**
   * e.g., "per lb", "per dozen", "per bale"
   */
  priceUnit?: string | null;
  availability: 'available' | 'seasonal' | 'sold-out' | 'pre-order';
  /**
   * e.g., "Available in November only"
   */
  seasonalNote?: string | null;
  qualityBadges?:
    | (
        | 'grass-fed'
        | 'pasture-raised'
        | 'no-hormones'
        | 'no-steroids'
        | 'no-antibiotics'
        | 'federally-inspected'
        | 'farm-fresh'
      )[]
    | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  author: string;
  quote: string;
  rating?: number | null;
  source?: ('google' | 'facebook' | 'direct') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  role: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortBio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  file: number | Media;
  category?: ('waiver' | 'contract' | 'menu' | 'form' | 'other') | null;
  requiresSignature?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure the smart inquiry wizard branches and questions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-flow-config".
 */
export interface InquiryFlowConfig {
  id: number;
  tenant?: (number | null) | Tenant;
  title?: string | null;
  introHeading?: string | null;
  introText?: string | null;
  branches?:
    | {
        /**
         * Unique identifier (e.g., "animal-sales", "events")
         */
        branchId: string;
        label: string;
        description?: string | null;
        /**
         * Icon identifier for the frontend
         */
        icon?: string | null;
        questions?:
          | {
              /**
               * Unique field key (e.g., "animalType")
               */
              fieldName: string;
              label: string;
              inputType:
                | 'text'
                | 'textarea'
                | 'email'
                | 'phone'
                | 'select'
                | 'multi-select'
                | 'date'
                | 'date-range'
                | 'number'
                | 'checkbox';
              placeholder?: string | null;
              required?: boolean | null;
              options?:
                | {
                    label: string;
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactFields?: {
    showName?: boolean | null;
    showEmail?: boolean | null;
    showPhone?: boolean | null;
    showMessage?: boolean | null;
  };
  confirmationHeading?: string | null;
  confirmationText?: string | null;
  emailRouting: {
    defaultRecipient: string;
    /**
     * Comma-separated list of CC emails
     */
    ccEmails?: string | null;
    subjectPrefix?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-submissions".
 */
export interface InquirySubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  branchId: string;
  branchLabel?: string | null;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * All question/answer pairs from the inquiry
   */
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  additionalMessage?: string | null;
  status: 'new' | 'in-progress' | 'responded' | 'closed';
  /**
   * Private notes about this inquiry (not visible to client)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Global site settings (one per tenant)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  farmName: string;
  tagline?: string | null;
  contactEmail: string;
  /**
   * Phone number (may be hidden on site per client preference)
   */
  contactPhone?: string | null;
  showPhone?: boolean | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  appointmentOnly?: boolean | null;
  logo?: (number | null) | Media;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
  };
  /**
   * Override default theme colors
   */
  brandColors?: {
    primary?: string | null;
    secondary?: string | null;
    accent?: string | null;
  };
  facebookPixelId?: string | null;
  googleAnalyticsId?: string | null;
  aboutHeading?: string | null;
  aboutText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  footerText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'inquiry-flow-config';
        value: number | InquiryFlowConfig;
      } | null)
    | ({
        relationTo: 'inquiry-submissions';
        value: number | InquirySubmission;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  status?: T;
  siteType?: T;
  ownerEmail?: T;
  ownerName?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  keyHash?: T;
  keyPrefix?: T;
  tenant?: T;
  status?: T;
  rateLimit?: T;
  lastUsedAt?: T;
  expiresAt?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  heroHeading?: T;
  heroSubheading?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  pricingText?: T;
  inquiryType?: T;
  icon?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  image?: T;
  altText?: T;
  category?: T;
  description?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  shortDescription?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  image?: T;
  facebookEventId?: T;
  facebookEventUrl?: T;
  registrationUrl?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  price?: T;
  priceUnit?: T;
  availability?: T;
  seasonalNote?: T;
  qualityBadges?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  author?: T;
  quote?: T;
  rating?: T;
  source?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  role?: T;
  bio?: T;
  shortBio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  file?: T;
  category?: T;
  requiresSignature?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-flow-config_select".
 */
export interface InquiryFlowConfigSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  introHeading?: T;
  introText?: T;
  branches?:
    | T
    | {
        branchId?: T;
        label?: T;
        description?: T;
        icon?: T;
        questions?:
          | T
          | {
              fieldName?: T;
              label?: T;
              inputType?: T;
              placeholder?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  contactFields?:
    | T
    | {
        showName?: T;
        showEmail?: T;
        showPhone?: T;
        showMessage?: T;
      };
  confirmationHeading?: T;
  confirmationText?: T;
  emailRouting?:
    | T
    | {
        defaultRecipient?: T;
        ccEmails?: T;
        subjectPrefix?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-submissions_select".
 */
export interface InquirySubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  branchId?: T;
  branchLabel?: T;
  name?: T;
  email?: T;
  phone?: T;
  answers?: T;
  additionalMessage?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  farmName?: T;
  tagline?: T;
  contactEmail?: T;
  contactPhone?: T;
  showPhone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  appointmentOnly?: T;
  logo?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
        youtube?: T;
      };
  brandColors?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
      };
  facebookPixelId?: T;
  googleAnalyticsId?: T;
  aboutHeading?: T;
  aboutText?: T;
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}